### ISSUE TITLE
Would the Portenta Breakout board help

### ISSUE THREAD

**Issue by hpssjellis** [Lennart401/PortentaTouchScreen#1]
This library is really interesting. I have both the seeduino TFT V2 and the Portenta with Breakout board. Any chance if that might make things a bit easier to work with?

ignore the arrows.
![image](https://user-images.githubusercontent.com/5605614/131916381-e6541ccb-1d79-49f2-a669-59ab6cc64b77.png)

**Comment by Lennart401** [comment]
So the main problem is that the portenta does simply not have 2 independent analog I/O pins on its header. Pin `A6` is the only usable one, while `A4` and `A5` are directly connected to `D8` and `D10` on the other side of the breadboard (just check using a multimeter), which are the SPI pins. Pins `A0`-`A3` are input-only and therefore of no use.

The board does have a few more analog pins which should be accessible using the high-density connectors. I've had a look at the pinout diagram and the stm32 pin definitions and identified three candidates that might be suitable as analog I/O pins:

1. PA0 I/O FT_a (I/O, 5V tolerant, analog option) -> `J1_34`
2. PA4 I/O TT_a (I/O, 3.3V tolerant, analog option) -> `J2_78` / `J2_22` (should be the same pin)
3. PA6 I/O FT_a (I/0, 5V tolerant, analog option) -> `J2_20`

Only pins `XL` "x left" (`A1` on the TFT V2) and `YU` "y up" (`A2` on the TFT V2) need to be connected to analog I/O pins (as we have to read an analog voltage from them), the other two can be digital pins.

I suggest you try and connect `XL` and `YU` to two of the pins mentioned above and see if you can get the touchscreen to work using that. `YD` "y down" and `XR` "x right" can be connected to any regular digital I/O pins. 

	#define YD ... // any free digital I/O pin
	#define XL PA_0 // might be wrong about the arduino PinName enum
	#define YU PA_4
	#define XR ... // any free digital I/O pin

	PortentaTouchScreen ts(YD, XL, YU, XR);

Maybe also try to get sensible readings from the touchscreen without connecting the TFT itself (i.e. 5V, GND, Reset and the SPI pins) to rule out any interference with that.

I'd really appreciate to hear back from you if that worked.

**Comment by hpssjellis** [comment]
@Lennart401 

I will try to find time to do this soon. To just test the touchscreen component I feel that I should have GND connected with the 4 pins you mention. Does that make sense?

By the way I am making a High School course around the Portenta so the final code will go here. Thanks for all your input. https://github.com/hpssjellis/maker100#29

**Comment by Lennart401** [comment]
Excellent!

And no, you don't need to have ground connected since it is nowhere connected with the touchscreen.

To read from the touchscreen, the library will create a potential over the x axis (write LOW to XL and HIGH to XR) and perform an analog read on of the y-Pins and vice versa. Depending on the axis the library reads, it'll create its on ground reference by writing LOW/0 to one of the pins of the axis.

I hope that explanation helps :)

**Comment by hpssjellis** [comment]
Yup, makes sense, I should have thought of that myself, but just assumed they were all inputs. Good explanation. 

P.S. You do any other stuff with the Portenta?

**Comment by hpssjellis** [comment]
Just checking. The following looks like on my charts


"D0"    PA0 I/O FT_a (I/O, 5V tolerant, analog option) -> J1_34
"D4"     PA4 I/O TT_a (I/O, 3.3V tolerant, analog option) -> J2_78 / J2_22 (should be the same pin)

"D6"  PA6 I/O FT_a (I/0, 5V tolerant, analog option) -> J2_20


Which should be easy to check without the breakout board.


My incomplete reference is at 

https://github.com/hpssjellis/my-examples-for-the-arduino-portentaH7/blob/master/PINS/Portenta-pins-working-copy.csv

**Comment by Lennart401** [comment]
> P.S. You do any other stuff with the Portenta?

Yes, I have a larger project at my university in the realm of IoT/Industry 4.0. All the code for that is published in my [LernfabrikArduino](https://github.com/Lennart401/LernfabrikArduino) repository. The project is not really designed around the portenta, it could probably use can STM32H7 microcontroller with sufficient RAM (and a few modifications to the code).

> "D0" PA0 I/O FT_a (I/O, 5V tolerant, analog option) -> J1_34
> "D4" PA4 I/O TT_a (I/O, 3.3V tolerant, analog option) -> J2_78 / J2_22 (should be the same pin)
> 
> "D6" PA6 I/O FT_a (I/0, 5V tolerant, analog option) -> J2_20

That's interesting. On the [Portenta Pinout datasheet](https://content.arduino.cc/assets/Pinout-PortentaH7_latest.pdf) I get the following descriptions for pins D0, D4 and D6

```
D0 | PH15 | PWM 7 | J2-62   (rather than D0 | PA0 | PWM 6 | J1-34 from your reference)
D4 | PC7  | PWM 3 | J2-63   (rather than D4 | PA4 | PWM 2 | J2-78 from your reference)
D6 | PA8  | PWM 1 | J2-59   (rather than D6 | PA6 | PWM 0 | J2-20 from your reference)
```

So if I understand this correctly, D0 should not be PA0, D4 should not be PA4 and so on. But I might be wrong on this one. Unfortunately, I don't have the portenta breakout board, otherwise I would check continuity between D0 (on the header) and J1-34 etc.

**Comment by hpssjellis** [comment]
@Lennart401 You are correct that D0, D6 don't work,  I get the red flash of death  (Scared to test D4 = PA_4 as not 5V tolerant). Unfortunately PA_0 and PA_6 are also giving me the ref flash of death so that looks like it is not an option.

  But success so far that "A7" does work for the pressure readings using the Portenta Breakout board. I will try to make some code that tests text, shapes and pressure.

**Comment by Lennart401** [comment]
Just for the record:
I think from issue #2 we can conclude that there are analog pins (namely A6 and A7, the latter one is only accessible using the breakout board) that do work. I'll adjust the example code for this and include a brief explanation on connecting the touchscreen and close this issue.

For anyone reading through this at a later point: have a look issue #2, there is more information on the topic.
